# Generated by Django 5.1.6 on 2025-02-25 21:26

import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgposts/')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(blank=True, max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgposts/')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='حدد وقت النشر')),
                ('views', models.IntegerField(default=0)),
                ('card_location', models.CharField(choices=[('1', 'Card left small'), ('2', 'Card center'), ('3', 'Card right small'), ('4', 'Card one'), ('5', 'Card two'), ('6', 'Card three'), ('7', 'Card Boss'), ('8', 'Card four'), ('9', 'Card five'), ('10', 'Card sex'), ('11', 'Card seven'), ('12', 'Card eight'), ('13', 'Card nine'), ('other', 'Other'), ('gust_post', 'Gust_post')], default='other', help_text='حدد مكان عرض البوست', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='posts.posts')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'ip_address'], name='posts_postv_post_id_6c0b9e_idx'), models.Index(fields=['timestamp'], name='posts_postv_timesta_6f46e7_idx')],
            },
        ),
    ]
