# Generated by Django 5.1.6 on 2025-02-26 20:03

import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_card_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='card_location',
            field=models.CharField(choices=[('1', 'Card left small'), ('2', 'Card center'), ('3', 'Card right small'), ('4', 'Card one'), ('5', 'Card two'), ('6', 'Card three'), ('7', 'Card Boss'), ('8', 'Card four'), ('9', 'Card five'), ('10', 'Card sex'), ('11', 'Card seven'), ('12', 'Card eight'), ('13', 'Card nine'), ('other', 'Other'), ('gust_post', 'Gust_post')], default='other', help_text='حدد مكان عرض البوست', max_length=10),
        ),
        migrations.CreateModel(
            name='Championships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(blank=True, max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgposts/')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='حدد وقت النشر')),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(blank=True, max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgposts/')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='حدد وقت النشر')),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(blank=True, max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgposts/')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='حدد وقت النشر')),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(blank=True, max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgposts/')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='حدد وقت النشر')),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
