# Generated by Django 5.1.6 on 2025-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
