# Generated by Django 5.1.6 on 2025-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_posts_card_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
